sudo: false
language: node_js
node_js:
- '6.0'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
script:
- npm run build
- npm test
after_success:
- bash ./scripts/deploy.sh
env:
  global:
  - GH_USER: rijkaa
  - GH_REPO: rijkaa.github.io
